# Generated by Django 5.2.5 on 2025-09-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_badge_userbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
