# Generated by Django 5.2.5 on 2025-09-01 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userprofile_last_activity_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('primary_language', models.CharField(choices=[('es', 'Español'), ('it', 'Italiano'), ('pt', 'Português'), ('ca', 'Català'), ('fr', 'Français')], default='es', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created this word', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='WordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar_note', models.TextField(help_text='Detailed grammatical explanation')),
                ('usage_example', models.TextField(blank=True, help_text='Example sentence using the word')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='intermediate', max_length=20)),
                ('etymology', models.TextField(blank=True, help_text='Word origin and etymology')),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='definition', to='authentication.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserSavedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('mastery_level', models.CharField(choices=[('new', 'Nouveau'), ('learning', 'En cours'), ('known', 'Connu'), ('mastered', 'Maîtrisé')], default='new', max_length=20)),
                ('saved_from_article', models.ForeignKey(blank=True, help_text='Article where user discovered this word', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.word')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.CreateModel(
            name='ArticleWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_text', models.PositiveIntegerField(help_text='Character position where word appears in article')),
                ('context_sentence', models.TextField(blank=True, help_text='The sentence where this word appears')),
                ('is_key_vocabulary', models.BooleanField(default=True, help_text='Whether this word is highlighted as key vocabulary')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_words', to='authentication.article')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_articles', to='authentication.word')),
            ],
            options={
                'ordering': ['position_in_text'],
                'unique_together': {('article', 'word', 'position_in_text')},
            },
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('it', 'Italiano'), ('pt', 'Português'), ('ca', 'Català'), ('fr', 'Français')], max_length=5)),
                ('translation', models.CharField(max_length=200)),
                ('pronunciation', models.CharField(blank=True, max_length=200)),
                ('part_of_speech', models.CharField(blank=True, choices=[('noun', 'Nom'), ('verb', 'Verbe'), ('adjective', 'Adjectif'), ('adverb', 'Adverbe'), ('preposition', 'Préposition'), ('article', 'Article'), ('other', 'Autre')], max_length=20)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='authentication.word')),
            ],
            options={
                'unique_together': {('word', 'language')},
            },
        ),
    ]
