# Generated by Django 5.2.5 on 2025-09-04 21:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('points_required', models.PositiveIntegerField(default=0)),
                ('quiz_count_required', models.PositiveIntegerField(default=0)),
                ('streak_required', models.PositiveIntegerField(default=0)),
                ('articles_read_required', models.PositiveIntegerField(default=0)),
                ('words_learned_required', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('progress', 'Progress'), ('achievement', 'Achievement'), ('streak', 'Streak'), ('learning', 'Learning'), ('special', 'Special')], default='progress', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['category', 'points_required'],
            },
        ),
        migrations.CreateModel(
            name='ContentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('es', 'Español'), ('it', 'Italiano'), ('pt', 'Português'), ('ca', 'Català'), ('fr', 'Français')], max_length=5)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Content Series',
                'verbose_name_plural': 'Content Series',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('language', models.CharField(choices=[('es', 'Español'), ('it', 'Italiano'), ('pt', 'Português'), ('ca', 'Català'), ('fr', 'Français')], max_length=5)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('publication_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, help_text='Brief article summary')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('author', models.ForeignKey(blank=True, help_text='Content creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linguaromana_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Quiz title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Quiz description')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Minimum score required to pass (percentage)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (optional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(help_text='Article that this quiz is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.article')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('es', 'Español'), ('it', 'Italiano'), ('pt', 'Português'), ('ca', 'Català'), ('fr', 'Français')], default='es', max_length=5)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('primary_language', models.CharField(choices=[('es', 'Español'), ('it', 'Italiano'), ('pt', 'Português'), ('ca', 'Català'), ('fr', 'Français')], default='es', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created this word', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linguaromana_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='WordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar_note', models.TextField(help_text='Detailed grammatical explanation')),
                ('usage_example', models.TextField(blank=True, help_text='Example sentence using the word')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='intermediate', max_length=20)),
                ('etymology', models.TextField(blank=True, help_text='Word origin and etymology')),
                ('memory_tip', models.TextField(blank=True, help_text='Mnemonic or memory aid')),
                ('common_mistakes', models.TextField(blank=True, help_text='Common usage mistakes to avoid')),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='definition', to='core.word')),
            ],
            options={
                'verbose_name': 'Word Definition',
                'verbose_name_plural': 'Word Definitions',
            },
        ),
        migrations.CreateModel(
            name='ArticleGrammarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Grammar note title', max_length=200)),
                ('content', models.TextField(help_text='Detailed grammar explanation')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order within the article')),
                ('is_key_concept', models.BooleanField(default=True, help_text='Whether this is a key grammar concept')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(help_text='Article this grammar note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grammar_notes', to='core.article')),
                ('word_definition', models.ForeignKey(help_text='Word definition this note explains', on_delete=django.db.models.deletion.CASCADE, related_name='article_grammar_notes', to='core.worddefinition')),
            ],
            options={
                'verbose_name': 'Article Grammar Note',
                'verbose_name_plural': 'Article Grammar Notes',
                'ordering': ['order', 'title'],
                'unique_together': {('article', 'word_definition')},
            },
        ),
        migrations.CreateModel(
            name='ArticleSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_series', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contentseries')),
            ],
            options={
                'verbose_name': 'Article Series',
                'verbose_name_plural': 'Article Series',
                'ordering': ['order_in_series'],
                'unique_together': {('article', 'series')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('articles_read', models.PositiveIntegerField(default=0)),
                ('quizzes_completed', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Result',
                'verbose_name_plural': 'Quiz Results',
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='UserSavedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('progress_level', models.CharField(choices=[('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='learning', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.word')),
            ],
            options={
                'verbose_name': 'Saved Word',
                'verbose_name_plural': 'Saved Words',
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.CreateModel(
            name='ArticleWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_text', models.PositiveIntegerField(help_text='Character position where word appears in article')),
                ('context_sentence', models.TextField(blank=True, help_text='The sentence where this word appears')),
                ('is_key_vocabulary', models.BooleanField(default=True, help_text='Whether this word is highlighted as key vocabulary')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_words', to='core.article')),
                ('grammar_note', models.OneToOneField(blank=True, help_text='Grammar note explaining this word in this article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_word', to='core.articlegrammarnote')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_articles', to='core.word')),
            ],
            options={
                'verbose_name': 'Article Word',
                'verbose_name_plural': 'Article Words',
                'ordering': ['position_in_text'],
                'unique_together': {('article', 'word', 'position_in_text')},
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('points', models.PositiveIntegerField(default=10)),
                ('question_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('comprehension', 'Comprehension'), ('translation', 'Translation')], default='vocabulary', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions_temp', to='core.article')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz')),
                ('word_definition', models.ForeignKey(help_text='The word definition this question tests', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='core.worddefinition')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'unique_together': {('quiz', 'word_definition')},
            },
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('it', 'Italiano'), ('pt', 'Português'), ('ca', 'Català'), ('fr', 'Français')], max_length=5)),
                ('translation', models.CharField(max_length=200)),
                ('pronunciation', models.CharField(blank=True, max_length=200)),
                ('part_of_speech', models.CharField(blank=True, choices=[('noun', 'Nom'), ('verb', 'Verbe'), ('adjective', 'Adjectif'), ('adverb', 'Adverbe'), ('preposition', 'Préposition'), ('article', 'Article'), ('other', 'Autre')], max_length=20)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.word')),
            ],
            options={
                'verbose_name': 'Word Translation',
                'verbose_name_plural': 'Word Translations',
                'unique_together': {('word', 'language')},
            },
        ),
    ]
