# Generated by Django 5.2.5 on 2025-09-07 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Content creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlegrammarnote',
            name='article',
            field=models.ForeignKey(help_text='Article this grammar note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='detailed_grammar_notes', to='core.article'),
        ),
        migrations.AlterField(
            model_name='word',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who created this word', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GrammarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Grammar note title', max_length=200)),
                ('content', models.TextField(help_text='Main grammar explanation for the article')),
                ('key_concepts', models.TextField(blank=True, help_text='Key grammar concepts covered in this article')),
                ('learning_objectives', models.TextField(blank=True, help_text='What students should learn from this grammar note')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', help_text='Grammar difficulty level', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(help_text='Article this grammar note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grammar_note', to='core.article')),
            ],
            options={
                'verbose_name': 'Grammar Note',
                'verbose_name_plural': 'Grammar Notes',
            },
        ),
    ]
