# Generated by Django 5.2.5 on 2025-09-07 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_grammar_note_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this comprehensive view')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this complete set is published and ready for students')),
                ('article', models.OneToOneField(help_text='Associated article', on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_view', to='core.article')),
                ('grammar_note', models.OneToOneField(help_text='Associated grammar note', on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_view', to='core.grammarnote')),
                ('quiz', models.OneToOneField(help_text='Associated quiz', on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_view', to='core.quiz')),
            ],
            options={
                'verbose_name': 'Comprehensive Article',
                'verbose_name_plural': 'Comprehensive Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
