# Generated by Django 5.2.5 on 2025-09-15 18:11

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_comprehensive_article_with_foreign_keys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Article title", max_length=200)),
                ("content", models.TextField(help_text="Article content")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("es", "Español"),
                            ("it", "Italiano"),
                            ("pt", "Português"),
                            ("ca", "Català"),
                            ("fr", "Français"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        help_text="Article difficulty level",
                        max_length=20,
                    ),
                ),
                ("publication_date", models.DateField(default=datetime.date.today)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Brief article summary"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
                (
                    "quiz_title",
                    models.CharField(
                        blank=True, help_text="Quiz title", max_length=200
                    ),
                ),
                (
                    "quiz_description",
                    models.TextField(blank=True, help_text="Quiz description"),
                ),
                (
                    "quiz_passing_score",
                    models.PositiveIntegerField(
                        default=70,
                        help_text="Minimum score required to pass (percentage)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "quiz_time_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time limit in minutes (optional)",
                        null=True,
                    ),
                ),
                ("quiz_is_active", models.BooleanField(default=True)),
                (
                    "grammar_title",
                    models.CharField(
                        blank=True, help_text="Main grammar note title", max_length=200
                    ),
                ),
                (
                    "grammar_content",
                    models.TextField(
                        blank=True, help_text="Main grammar explanation for the article"
                    ),
                ),
                (
                    "grammar_key_concepts",
                    models.TextField(
                        blank=True,
                        help_text="Key grammar concepts covered in this article",
                    ),
                ),
                (
                    "grammar_learning_objectives",
                    models.TextField(
                        blank=True,
                        help_text="What students should learn from this grammar note",
                    ),
                ),
                (
                    "grammar_difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        help_text="Grammar difficulty level",
                        max_length=20,
                    ),
                ),
                (
                    "quiz_questions_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of quiz questions with all their data",
                    ),
                ),
                (
                    "detailed_grammar_notes_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of detailed grammar notes for specific words",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Content creator",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unified_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unified Article",
                "verbose_name_plural": "Unified Articles",
                "ordering": ["-publication_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["language", "level"],
                        name="core_unifie_languag_0feef2_idx",
                    ),
                    models.Index(
                        fields=["publication_date", "is_active"],
                        name="core_unifie_publica_e26129_idx",
                    ),
                    models.Index(
                        fields=["author"], name="core_unifie_author__67aefc_idx"
                    ),
                ],
            },
        ),
    ]
