# Generated by Django 5.2.5 on 2025-09-15 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_unified_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleseries",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.unifiedarticle"
            ),
        ),
        migrations.AlterField(
            model_name="userquizresult",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.unifiedarticle"
            ),
        ),
    ]
